### PR TITLE
fix: parse JSON errors

### LINKED ISSUE #115: JSON errors results in crashing of module
Healthcheck error responses are stringfied Arsenal errors. The module currently crashes when the response body is JSON.

### PR DESCRIPTION
**Pull request by rahulreddy**
fixes #115

### CODE REVIEW

**Comment by rahulreddy** [comment]
@ironman-machine try

**Comment by rahulreddy** [comment]
@ironman-machine try

**Comment by rahulreddy** [comment]
End to end passed here http://ci.ironmann.io/gh/scality/Integration/8442

**Comment by rahulreddy** [comment]
@alexandre-merle I know it's a deviation from the traditional responses. But this helps keeping the error responses for healthchecks be consistent.

**Comment by alexandre-merle** [comment]
@ironman-machine clean r+

**Pull request merged**
