### PR TITLE
VLTCLT-7 Upgrade Node from 10 to 16

### PR DESCRIPTION
**Pull request by dimitri-bourreau**
This PR aims to upgrade Node 10 to 16.

### CODE REVIEW

**Comment by dimitri-bourreau** [comment]
Fix versions are updated.

**Review by miniscruff — APPROVED** [review]

**Comment by dimitri-bourreau** [comment]
Thanks to [your comment in Arsenal's PR](https://github.com/scality/Arsenal/pull/1649#pullrequestreview-825585260) @miniscruff , I've also updated here the package.json's engines here. 👍

**Review by miniscruff — APPROVED** [review]

**Review by rahulreddy — COMMENTED** [review]
You have to regenerate the yarn.lock file correct?

**Comment by dimitri-bourreau** [comment]
> You have to regenerate the yarn.lock file correct?

Indeed. I just did it.
Linting fails but fixing it must be easy.

About dependencies:

## Upgrades
I will do a commit upgrading everything.
If CI fails, I'll revert the commit and apply the only minor upgrade of babel-eslint.

## Dependency analysis
`yarn upgrade-interactive` only finds Scality's dependencies to update (arsenal, werelogs, eslint-config-scality).
Those can not be upgraded automatically, we should define ourself which version to upgrade to.

`npx npm-check -u`
- (minor update - dev dependency) babel-eslint..................10.0.2 > 10.1.0
- (major update - dev dependency) eslint.............................6.0.1   > 8.4.1
- (major update - dev dependency) eslint-config-airbnb.....17.1.0  > 19.0.2
- (major update - dev dependency) mocha..........................6.1.4   > 9.1.3
- (major update) commander................................................2.20.0 > 8.3.0
- xml2js..................................................................................0.4.19 > 0.4.23

**Comment by dimitri-bourreau** [comment]
@rahulreddy `yarn.lock` has been regenerated, CI is green. ✅

**Comment by dimitri-bourreau** [comment]
> ```shell
> git push -u origin w/7.10/improvement/VLTCLT-7-upgrade-nodejs
> ```

Done. ✅

**Comment by miniscruff** [comment]
Closing in favor of the one i made

**Pull request closed without merging**
