### PR TITLE
improvement/S3C-2359-migrate package manager to yarn

### PR DESCRIPTION
**Pull request by Katherinelaue1**
**What does this PR do, and why do we need it?**
Migrate package manager to yarn

**Which issue does this PR fix?**
fixes #S3C-2359

**Special notes for your reviewers:**

### CODE REVIEW

**Comment by Katherinelaue1** [comment]
@bert-e status

**Comment by Katherinelaue1** [comment]
test

**Comment by Katherinelaue1** [comment]
@bert-e reset

**Comment by Katherinelaue1** [comment]
test

**Review by JianqinWang — APPROVED** [review]

**Review by jonathan-gramain — APPROVED** [review]

**Review by rahulreddy — APPROVED** [review]

**Comment by Katherinelaue1** [comment]
@bert-e approve

**Pull request merged**
