### PR TITLE
Port/fwdport6.3 master

### PR DESCRIPTION
**Pull request by rahulreddy**

### CODE REVIEW

**Comment by rahulreddy** [comment]
@ironman-machine

**Comment by rahulreddy** [comment]
@ironman-machine try

**Comment by rahulreddy** [comment]
@alexandre-merle Can you please merge this?

**Comment by alexandre-merle** [comment]
@ironman-machine r+

**Comment by DavidPineauScality** [comment]
@ironman-machine r+

**Comment by DavidPineauScality** [comment]
I only re-made the forward port due to the branch switch, and the diff hasn't changed, which was the expected result. As such, I'm merging, considering the previous reviews.

**Comment by DavidPineauScality** [comment]
http://ci.ironmann.io/gh/scality/Integration/8825 was the automatic retry of this PR.
Merging manually to avoid running ultron again.

**Pull request merged**
