### PR TITLE
S3C-4656 Make account seeding optional

### PR DESCRIPTION
**Pull request by nicolas2bert**

### CODE REVIEW

**Review by rachedbenmustapha — APPROVED** [review]

**Review by naren-rajendran — APPROVED** [review]

**Review by jonathan-gramain — APPROVED** [review]

**Review by anurag4DSB — COMMENTED** [review]
Should this be a part of create account as well?

**Comment by nicolas2bert** [comment]
I don't think we want our customers to be able to disable seeding because it plays a key role in "management account authentication".

**Comment by nicolas2bert** [comment]
@bert-e approve

**Pull request merged**
