### PR TITLE
Fwdport/6.4 master

### PR DESCRIPTION
**Pull request by rahulreddy**

### CODE REVIEW

**Comment by rahulreddy** [comment]
@ironman-machine try

**Comment by bennettbuchanan** [comment]
@ironman-machine try

**Comment by bennettbuchanan** [comment]
@ironman-machine
SCALITY_VAULT_BRANCH=fwdport/6.4-master
SCALITY_INTEGRATION_BRANCH=forward/rel/6.4
try

**Comment by bennettbuchanan** [comment]
E2E passed without dependency branches. http://ci.ironmann.io/gh/scality/Integration/11407

**Comment by bennettbuchanan** [comment]
@ironman-machine
SCALITY_VAULT_BRANCH=fwdport/6.4-master
SCALITY_INTEGRATION_BRANCH=forward/rel/6.4
SCALITY_UTAPI_BRANCH=forward/rel/6.4
try

**Comment by vrancurel** [comment]
@ironman-machine r+

**Pull request merged**
