### PR TITLE
feature: VLTCLT-23-add-custom-attribute

### PR DESCRIPTION
**Pull request by anurag4DSB**
allows add account attribute via CLI

### CODE REVIEW

**Review by XinLi0207 — APPROVED** [review]

**Review by ghost — APPROVED** [review]
If a release is expected, you can bump the package.json version before merging the PR :slightly_smiling_face:

**Comment by anurag4DSB** [comment]
> If a release is expected, you can bump the package.json version before merging the PR 🙂

Great idea, we will do it with the next PR(we have one more)

**Pull request merged**
