### PR TITLE
ZENKO-2604 add ability to pass a context and request options

### PR DESCRIPTION
**Pull request by nicolas2bert**
This will add the ability to use (non-exhaustive):

- context for request cancellation
- options to the retrieve headers from the HTTP response and assign them to the passed in headers variable
- options to set the request to use a specific log level when the request is made

### CODE REVIEW

**Review by rahulreddy — APPROVED** [review]
/bypass_peer_approval

**Review by jonathan-gramain — APPROVED** [review]

**Comment by nicolas2bert** [comment]
@bert-e approve

**Pull request merged**
